const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const root=process.env.TAXCOMPRO_TEST_ROOT||path.resolve(__dirname,'..'),ts=require(path.join(root,'node_modules/typescript'));
let session=null,enrolled=false,ownedLesson=false,writes=0;
const quiz={id:'quiz',questions:[{id:'question',question:'Question',options:['A','B'],correctAnswer:1,explanation:'Secret answer',order:0}]};
const lesson={id:'lesson',isFree:false,videoUrl:'https://paid.example.test/video',downloadUrl:'https://paid.example.test/file',textContent:'<p>Content</p><img src="x" onerror="alert(1)">',quiz};
const course={id:'course',slug:'course',status:'PUBLISHED',instructorId:'owner',sections:[{lessons:[lesson,{...lesson,id:'preview',isFree:true}]}]};
const prisma={course:{findUnique:async()=>course},user:{findUnique:async()=>({role:'MEMBER',id:'buyer'})},enrollment:{findUnique:async()=>enrolled?{id:'enrollment',progress:[]}:null},marketplacePurchase:{findFirst:async()=>null},courseRating:{findMany:async()=>[]},lesson:{findFirst:async()=>ownedLesson?lesson:null},lessonProgress:{upsert:async()=>{writes++;}},quiz:{findUnique:async()=>{throw Error('Unauthorized quiz access');}}};
const cache={};function load(file){if(cache[file])return cache[file];const m={exports:{}};const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;const mocks={'@/lib/prisma':{prisma},'@/lib/auth':{auth:{api:{getSession:async()=>session}}},'next/headers':{headers:async()=>new Headers()},'next/server':{NextResponse:{json:(data,init)=>({data,status:init?.status||200})}}};vm.runInThisContext('(function(require,module,exports){'+code+'})')(id=>mocks[id]||(id.startsWith('@/')?load(id.slice(2)+'.ts'):require(require.resolve(id,{paths:[root]}))),m,m.exports);return cache[file]=m.exports;}
(async()=>{const route=load('app/api/courses/[slug]/route.ts'),params={params:Promise.resolve({slug:'course'})},req={headers:new Headers(),json:async()=>({lessonId:'other-course-lesson',answers:[1]})};let response=await route.GET(req,params);assert.equal(response.data.sections[0].lessons[0].textContent,null);assert.equal(response.data.sections[0].lessons[0].videoUrl,null);assert.equal(response.data.sections[0].lessons[0].downloadUrl,null);assert(!response.data.sections[0].lessons[1].textContent.includes('onerror'));session={user:{id:'buyer'}};enrolled=true;response=await route.GET(req,params);assert(response.data.sections[0].lessons[0].textContent.includes('Content'));assert.equal(response.data.sections[0].lessons[0].quiz.questions[0].correctAnswer,undefined);assert.equal(response.data.sections[0].lessons[0].quiz.questions[0].explanation,undefined);assert.equal((await load('app/api/courses/[slug]/progress/route.ts').POST(req,params)).status,404);assert.equal((await load('app/api/courses/[slug]/quiz-attempt/route.ts').POST(req,params)).status,404);assert.equal(writes,0);console.log('PASS 4 course-security scenarios: locked content hidden, free preview sanitized, enrolled content without answer keys, cross-course progress and quiz access rejected.');})().catch(e=>{console.error(e);process.exitCode=1});
