const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const root=process.env.TAXCOMPRO_TEST_ROOT||path.resolve(__dirname,'..'),ts=require(path.join(root,'node_modules/typescript'));
let session={user:{id:'existing',phone:null}},saved=null;const prisma={user:{findUnique:async()=>({phone:session.user.phone}),update:async(args)=>{saved=args;return{id:'existing'};}}};
const cache={};function load(file){if(cache[file])return cache[file];const m={exports:{}};const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;const mocks={'@/lib/prisma':{prisma},'@/lib/auth':{auth:{api:{getSession:async()=>session}}},'@/lib/request-security':{protectApiRequest:async()=>null},'next/server':{NextResponse:{json:(data,opts)=>({data,status:opts?.status||200}),redirect:url=>({status:307,url:String(url)}),next:()=>({status:200})}}};vm.runInThisContext('(function(require,module,exports){'+code+'})')(id=>mocks[id]||(id.startsWith('@/')?load(id.slice(2)+'.ts'):require(id)),m,m.exports);return cache[file]=m.exports;}
const req=(path,method='GET',body={})=>({headers:new Headers(),nextUrl:new URL('https://taxcomppro.com'+path),url:'https://taxcomppro.com'+path,method,json:async()=>body});
(async()=>{const phone=load('lib/phone-number.ts'),api=load('app/api/user/phone/route.ts'),{proxy}=load('proxy.ts');assert.equal(phone.normalizePhoneNumber('+1 (555) 123-4567'),'+15551234567');for(const invalid of ['',null,'1234','+0 123456789','+1abc5551234567'])assert.equal(phone.normalizePhoneNumber(invalid),null);for (const local of ['5551234567', '(555) 123-4567', '1 555 123 4567']) assert.equal(phone.normalizePhoneNumber(local), '+15551234567');assert.equal(phone.phoneReturnPath('//evil.test'),'/feed');assert.equal(phone.phoneReturnPath('/complete-profile?next=/x'),'/feed');assert.equal(phone.phoneReturnPath('/pro-talks/123?tab=host'),'/pro-talks/123?tab=host');
assert.equal((await api.GET(req('/api/user/phone'))).data.required,true);assert.equal((await api.PATCH(req('/api/user/phone','PATCH',{phone:'bad'}))).status,400);assert.equal(saved,null);assert.equal((await api.PATCH(req('/api/user/phone','PATCH',{phone:'+44 7700 900123',userId:'someone-else'}))).status,200);assert.deepEqual(saved.where,{id:'existing'});assert.deepEqual(saved.data,{phone:'+447700900123'});assert.equal((await api.PATCH(req('/api/user/phone','PATCH',{phone:'5551234567'}))).status,200);assert.deepEqual(saved.data,{phone:'+15551234567'});
assert.match((await proxy(req('/feed?tab=all'))).url,/complete-profile\?next=/);assert.equal((await proxy(req('/api/feed','POST'))).data.code,'PHONE_REQUIRED');assert.equal((await proxy(req('/api/user/phone','PATCH'))).status,200);assert.equal((await proxy(req('/api/auth/sign-out','POST'))).status,200);assert.equal((await proxy(req('/complete-profile'))).status,200);
session.user.phone='5551234567';assert.equal((await api.GET(req('/api/user/phone'))).data.required,false);assert.equal((await proxy(req('/feed'))).status,200);assert.equal((await proxy(req('/api/feed','POST'))).status,200);
session=null;assert.equal((await api.GET(req('/api/user/phone'))).status,401);assert.equal((await api.PATCH(req('/api/user/phone','PATCH',{phone:'+15551234567'}))).status,401);console.log('PASS phone validation, safe return paths, authenticated ownership, missing-phone page/API enforcement, save/sign-out exemptions, and existing-number access.');})().catch(e=>{console.error(e);process.exitCode=1});
