process.env.TZ = "UTC";
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const root=process.env.TAXCOMPRO_TEST_ROOT||path.resolve(__dirname,'..');
const ts=require(path.join(root,'node_modules/typescript'));
const {PGlite}=require(path.join(root,'node_modules/@electric-sql/pglite'));
const {NextRequest,NextResponse}=require(path.join(root,'node_modules/next/server'));
const db=new PGlite();let unavailable=false,checks=0;
process.env.BETTER_AUTH_SECRET='test-only-not-a-real-secret';process.env.NODE_ENV='production';process.env.VERCEL='1';
const sql=(strings,values)=>strings.reduce((s,part,i)=>s+(i?'$'+i:'')+part,'');
const raw=async(strings,...values)=>{if(unavailable)throw Error('offline');return (await db.query(sql(strings,values),values)).rows;};
const prisma={$queryRaw:raw,$executeRaw:raw};
const modules={};function load(file){if(modules[file])return modules[file];const m={exports:{}};const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;const mocks={'@/lib/prisma':{prisma},'next/server':{NextRequest,NextResponse},'@/lib/auth':{auth:{api:{getSession:async()=>null}}}};vm.runInThisContext('(function(require,module,exports){'+code+'})')(id=>mocks[id]||(id.startsWith('@/')?load(id.slice(2)+'.ts'):require(require.resolve(id,{paths:[root]}))),m,m.exports);return modules[file]=m.exports;}
const request=(pathname,method='GET',headers={},body)=>new NextRequest('https://taxcomppro.com'+pathname,{method,headers:{'x-vercel-forwarded-for':'198.51.100.17',...headers},...(body?{body}:{} )});
(async()=>{try{
await db.exec('CREATE TABLE verifications (id text PRIMARY KEY, identifier text NOT NULL, value text NOT NULL, "expiresAt" timestamp NOT NULL, "createdAt" timestamp NOT NULL, "updatedAt" timestamp NOT NULL)');
const {consumeRateLimit,enforceRateLimit,clientNetwork,trustedMutation,protectApiRequest,ratePolicy}=load('lib/request-security.ts');
let results=await Promise.all(Array.from({length:40},()=>consumeRateLimit('parallel',{key:'test',limit:10,seconds:60})));assert.equal(results.filter(r=>r.allowed).length,10);checks++;
assert((await consumeRateLimit('other',{key:'test',limit:10,seconds:60})).allowed);await db.exec(`UPDATE verifications SET "expiresAt"=NOW()-INTERVAL '1 second'`);assert((await consumeRateLimit('parallel',{key:'test',limit:10,seconds:60})).allowed);checks++;
const stored=(await db.query('SELECT id,identifier,value FROM verifications')).rows;assert(stored.every(row=>!row.id.includes('parallel')&&!row.id.includes('other')));checks++;
assert.equal(clientNetwork(new Headers({'x-vercel-forwarded-for':'2001:db8:1234:5678::1'})),clientNetwork(new Headers({'x-vercel-forwarded-for':'2001:db8:1234:5678::ffff'})));assert.equal(clientNetwork(new Headers({'x-vercel-forwarded-for':'::ffff:192.0.2.1'})),'192.0.2.1');assert.equal(clientNetwork(new Headers({'x-forwarded-for':'1.2.3.4'})),'unknown-network');checks++;
assert(trustedMutation(request('/api/feed','POST',{origin:'https://taxcomppro.com',cookie:'session=x'})));assert(trustedMutation(request('/api/feed','POST',{origin:'https://academy.taxcomppro.com'})));assert(!trustedMutation(request('/api/feed','POST',{origin:'https://evil.test',cookie:'session=x'})));assert(!trustedMutation(request('/api/feed','POST',{cookie:'session=x'})));assert(!trustedMutation(request('/api/feed','POST',{'sec-fetch-site':'cross-site'})));checks++;
assert.equal((await protectApiRequest(request('/api/feed','POST',{origin:'https://evil.test'}))).status,403);assert.equal((await protectApiRequest(request('/api/feed','POST',{'content-length':'2000000'}))).status,413);checks++;
for(let i=0;i<12;i++)assert.equal(await protectApiRequest(request('/api/auth/sign-in/email','POST',{'next-router-prefetch':'1'})),null);let blocked=await protectApiRequest(request('/api/%61uth/sign-in/email','POST',{'next-router-prefetch':'1'}));assert.equal(blocked.status,429);assert(Number(blocked.headers.get('Retry-After'))>0);checks++;
for(let i=0;i<20;i++)assert.equal(await protectApiRequest(request('/api/atlas-chat','POST',{'x-vercel-forwarded-for':'198.51.100.'+(i+20)}),async()=>'same-user'),null);assert.equal((await protectApiRequest(request('/api/atlas-chat','POST',{'x-vercel-forwarded-for':'198.51.100.99'}),async()=>'same-user')).status,429);checks++;
unavailable=true;assert.equal((await enforceRateLimit('x',{key:'test',limit:1,seconds:60})).status,503);assert.equal(await protectApiRequest(request('/api/stripe/webhook','POST',{origin:'https://stripe.com'})),null);assert.equal(await protectApiRequest(request('/api/cron/specialists')),null);unavailable=false;checks++;
const proxy=load('proxy.ts');assert.equal((await proxy.proxy(request('/%61pi/feed','POST',{origin:'https://evil.test','next-router-prefetch':'1'}))).status,403);assert.equal((await proxy.proxy(request('/api/auth/sign-up/email','POST'))).status,403);checks++;
const {validateUploads}=load('lib/upload-security.ts');assert.equal(await validateUploads([new File([Buffer.from('89504e470d0a1a0a','hex')],'image.png',{type:'image/png'})]),null);assert(await validateUploads([new File(['<svg onload="alert(1)">'],'image.svg',{type:'image/svg+xml'})]));assert(await validateUploads([new File(['MZ executable'],'image.png',{type:'image/png'})]));assert(await validateUploads(['fake']));assert(await validateUploads([new File(['%PDF-1.7'],'document.pdf',{type:'image/png'})]));assert(await validateUploads([new File(['1234'],'text.txt',{type:'text/plain'})],2));checks++;
const {guardAuthRequest}=load('lib/auth-request-guard.ts');for(let i=0;i<5;i++)assert.equal(await guardAuthRequest(request('/api/auth/request-password-reset','POST',{'content-type':'application/json'},JSON.stringify({email:'demo@example.test'}))),null);assert.equal((await guardAuthRequest(request('/api/auth/request-password-reset','POST',{'content-type':'application/json'},JSON.stringify({email:'DEMO@EXAMPLE.TEST'})))).status,429);assert.equal((await guardAuthRequest(request('/api/auth/sign-in/email','POST',{},'x'.repeat(65537)))).status,413);checks++;
assert.equal(ratePolicy('/api/spaces/one/checkout','POST').key,ratePolicy('/api/spaces/two/checkout','POST').key);assert.equal(ratePolicy('/api/upload-video','GET').key,'uploads');checks++;
prisma.$transaction=fn=>db.transaction(async tx=>fn({$executeRaw:(strings,...values)=>tx.query(sql(strings,values),values),verification:{
findFirst:async({where})=>(await tx.query('SELECT * FROM verifications WHERE identifier=$1 ORDER BY "createdAt" DESC LIMIT 1',[where.identifier])).rows[0]||null,
deleteMany:async({where})=>tx.query('DELETE FROM verifications WHERE identifier=$1',[where.identifier]),
create:async({data})=>tx.query('INSERT INTO verifications (id,identifier,value,"expiresAt","createdAt","updatedAt") VALUES ($1,$2,$3,$4,NOW(),NOW())',[require('node:crypto').randomUUID(),data.identifier,data.value,data.expiresAt]),
update:async({where,data})=>tx.query('UPDATE verifications SET value=$1 WHERE id=$2',[data.value,where.id]),
}}));
const otp=load('lib/otp.ts');const sends=await Promise.all(Array.from({length:8},()=>otp.createOtp('otp@example.test')));assert.equal(sends.filter(r=>r.ok).length,1);const code=sends.find(r=>r.ok).code;const verifications=await Promise.all(Array.from({length:8},()=>otp.verifyOtp('otp@example.test',code)));assert.equal(verifications.filter(r=>r.ok).length,1);checks++;
await otp.createOtp('guesses@example.test');const guesses=await Promise.all(Array.from({length:9},()=>otp.verifyOtp('guesses@example.test','invalid')));assert.equal(guesses.filter(r=>r.reason==='invalid').length,4);assert(guesses.every(r=>!r.ok));checks++;
const {safeRichText}=load('lib/safe-rich-text.ts');const html=safeRichText('<p>Hello <strong>world</strong></p><script>alert(1)</script><img src="https://example.test/a.png" onerror="alert(1)"><a href="javascript:alert(1)">bad</a><svg onload="alert(1)"></svg>');assert(html.includes('<strong>world</strong>'));assert(!/script|onerror|onload|javascript|<svg/.test(html));checks++;
console.log('PASS '+checks+' security scenarios with real in-memory PostgreSQL SQL: concurrent rate counts, expiry, identity privacy, IPv6 grouping, origin checks, spoofed/prefetch/encoded-path bypass attempts, account limits, 429/503, webhook preservation, upload signatures and credential body limits.');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1});
